# Question 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
JNJ = pd.read_csv("hw3_JNJ.csv")
MRK = pd.read_csv("hw3_MRK.csv")
PFE = pd.read_csv("hw3_PFE.csv")

In [3]:
JNJ

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-03-01,137.220001,138.610001,137.009995,138.350006,124.435135,5641600
1,2019-03-04,138.850006,139.410004,137.509995,138.479996,124.552055,8377700
2,2019-03-05,138.809998,139.139999,138.360001,138.770004,124.812874,6568900
3,2019-03-06,139.470001,139.649994,138.600006,139.089996,125.100700,6236900
4,2019-03-07,138.529999,139.119995,137.699997,138.240005,124.336174,6100400
...,...,...,...,...,...,...,...
498,2021-02-22,161.869995,162.539993,160.289993,161.869995,153.702560,6447100
499,2021-02-23,161.479996,163.190002,160.399994,160.440002,152.344727,7042800
500,2021-02-24,162.399994,164.389999,160.919998,162.589996,154.386230,10286100
501,2021-02-25,163.130005,163.699997,161.990005,162.759995,154.547684,9719700
502,2021-02-26,162.000000,162.410004,157.970001,158.460007,150.464630,14417500

In [4]:
MRK

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-03-01,78.015266,78.177483,77.452293,77.910301,68.250496,10624205
1,2019-03-04,78.272903,78.358780,76.841606,77.643127,68.016464,8522755
2,2019-03-05,77.748093,78.272903,77.500000,77.958015,68.292305,8698190
3,2019-03-06,77.862595,78.015266,76.622139,77.061066,67.506546,8167169
4,2019-03-07,77.318703,77.395035,76.374046,76.765266,67.247429,10925505
...,...,...,...,...,...,...,...
498,2021-02-22,71.087784,71.622139,70.353050,71.498093,66.382393,8612464
499,2021-02-23,71.841606,72.480919,71.049622,71.125954,66.036880,10900458
500,2021-02-24,71.374046,71.822517,70.982826,71.154579,66.063454,9838834
501,2021-02-25,70.811066,71.564888,70.687019,71.202293,66.107750,10906955
502,2021-02-26,71.030533,71.288170,69.217560,69.293892,64.335899,17644862

In [5]:
PFE

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-03-01,41.375713,41.546490,41.072105,41.138519,35.504776,26667781
1,2019-03-04,41.214420,41.356735,40.683113,40.863377,35.267315,22805820
2,2019-03-05,40.882355,41.034157,40.654648,40.692600,35.119923,26529812
3,2019-03-06,40.626186,40.673622,39.487667,39.715370,34.276524,22410359
4,2019-03-07,39.715370,39.743832,39.136623,39.269451,33.891674,29046132
...,...,...,...,...,...,...,...
498,2021-02-22,34.330002,34.369999,34.040001,34.259998,31.986647,34322500
499,2021-02-23,34.000000,34.189999,33.680000,33.910000,31.659872,37624200
500,2021-02-24,33.869999,34.049999,33.669998,33.750000,31.510492,30686100
501,2021-02-25,33.820000,34.110001,33.540001,33.820000,31.575851,37506100
502,2021-02-26,33.840000,33.900002,33.360001,33.490002,31.267750,41462800

In [43]:
# parametric VaR calculation separately using matrix formula
import numpy as np
import pandas as pd

# Define the portfolio and historical dataframes
portfolio = {"JNJ": 1.2*10**6,
             "MRK": 2.5*10**6,
             "PFE": 3.5*10**6
            }
JNJ = pd.read_csv("hw3_JNJ.csv")
MRK = pd.read_csv("hw3_MRK.csv")
PFE = pd.read_csv("hw3_PFE.csv")

# Use the most recent market price as the current market price
current_prices = {"JNJ": JNJ.iloc[-1]["Adj Close"],
                  "MRK": MRK.iloc[-1]["Adj Close"],
                  "PFE": PFE.iloc[-1]["Adj Close"]
                 }

JNJ_r = np.log(JNJ["Adj Close"]) - np.log(JNJ["Adj Close"].shift(1))
JNJ_r.dropna()
JNJ_r_ewm = JNJ_r.ewm(alpha=0.06, adjust=True).mean().dropna()

MRK_r = np.log(MRK["Adj Close"]) - np.log(MRK["Adj Close"].shift(1))
MRK_r.dropna()
MRK_r_ewm = MRK_r.ewm(alpha=0.06, adjust=True).mean().dropna()

PFE_r = np.log(PFE["Adj Close"]) - np.log(PFE["Adj Close"].shift(1))
PFE_r.dropna()
PFE_r_ewm = PFE_r.ewm(alpha=0.06, adjust=True).mean().dropna()

# Use the exponentially weighted average of daily returns to estimate the variance-covariance matrix
returns_ewm = pd.concat([JNJ_r_ewm, MRK_r_ewm, PFE_r_ewm], axis=1)
cov_ewm = returns_ewm.cov()

# Calculate the portfolio variance and volatility
portfolio_var = np.dot(np.dot(list(portfolio.values()), cov_ewm), list(portfolio.values()))
portfolio_vol = np.sqrt(portfolio_var)

# Compute the 1-day VaR (with 99% confidence) for the portfolio
confidence_level = 0.99
z_score = 2.33  # Z-score for 99% confidence level
one_day_VaR = portfolio_vol * z_score

# Print the results
print("Portfolio Variance: {:,.9f}".format(portfolio_var))
print("Portfolio Volatility: {:,.9f}".format(portfolio_vol))
print("1-day VaR (99% confidence): ${:,.9f}".format(one_day_VaR))

Portfolio Variance: 256,945,336.967374474
Portfolio Volatility: 16,029.514558070
1-day VaR (99% confidence): $37,348.768920303

In [44]:
# This is an alternative (more preferred ) solution by using the explicit formula without the linear algebra
ewm_mean1, ewm_std1 = JNJ_r_ewm, JNJ_r_ewm.std()
ewm_mean2, ewm_std2 = JNJ_r_ewm, JNJ_r_ewm.std()
ewm_mean3, ewm_std3 = JNJ_r_ewm, JNJ_r_ewm.std()

w1=1.2*10**6
w2=2.5*10**6
w3=3.5*10**6

variance_p = w1*w1*ewm_std1**2 + w2*w2*ewm_std2**2 + w3*w3*ewm_std3**2 + 2*w1*w2*JNJ_r_ewm.cov(other=MRK_r_ewm) + 2*w1*w3*JNJ_r_ewm.cov(other=PFE_r_ewm) + 2*w3*w2*MRK_r_ewm.cov(other=PFE_r_ewm)

#1 day 99% VaR
2.33*np.sqrt(variance_p)

32257.09009831806

In [45]:
# historical VaR calculation
import pandas as pd
import numpy as np
from datetime import datetime

# Define the portfolio and historical dataframes
portfolio = {"JNJ": 1.2*10**6,
             "MRK": 2.5*10**6,
             "PFE": 3.5*10**6
            }
JNJ = pd.read_csv("hw3_JNJ.csv")
MRK = pd.read_csv("hw3_MRK.csv")
PFE = pd.read_csv("hw3_PFE.csv")

# Use the most recent market price as the current market price
current_prices = {"JNJ": JNJ.iloc[-1]["Adj Close"],
                  "MRK": MRK.iloc[-1]["Adj Close"],
                  "PFE": PFE.iloc[-1]["Adj Close"]
                 }

JNJ_preds = []
MRK_preds = []
PFE_preds = []

JNJ_rates = []
MRK_rates = []
PFE_rates = []

JNJ_pos_future = []
MRK_pos_future = []
PFE_pos_future = []

for i in range(-2,-len(JNJ),-1):
    JNJ_cur = JNJ.iloc[i]["Adj Close"]
    JNJ_prev = JNJ.iloc[i-1]["Adj Close"]
    JNJ_change = np.log(JNJ_cur) - np.log(JNJ_prev)
    JNJ_pred = current_prices["JNJ"]*np.exp(JNJ_change)
    JNJ_preds.append(JNJ_pred)
    JNJ_rates.append(JNJ_change)
    JNJ_pos_future.append((JNJ_pred-current_prices["JNJ"])*1200000)
    
    MRK_cur = MRK.iloc[i]["Adj Close"]
    MRK_prev = MRK.iloc[i-1]["Adj Close"]
    MRK_change = np.log(MRK_cur) - np.log(MRK_prev)
    MRK_pred = current_prices["MRK"]*np.exp(MRK_change)
    MRK_preds.append(MRK_pred)
    MRK_rates.append(MRK_change)
    MRK_pos_future.append((MRK_pred-current_prices["MRK"])*2500000)
    
    PFE_cur = PFE.iloc[i]["Adj Close"]
    PFE_prev = PFE.iloc[i-1]["Adj Close"]
    PFE_change = np.log(PFE_cur) - np.log(PFE_prev)
    PFE_pred = current_prices["PFE"]*np.exp(PFE_change)
    PFE_preds.append(PFE_pred)
    PFE_rates.append(PFE_change)
    PFE_pos_future.append((PFE_pred-current_prices["PFE"])*3500000)
    
portfolio_pos_future = np.array(JNJ_pos_future) + np.array(MRK_pos_future) + np.array(PFE_pos_future)

confidence_level = 0.99
one_day_VaR = np.percentile(portfolio_pos_future, 0.99)
one_day_VaR

-19463059.121278007

In [46]:
# hist using method 2 as suggested by combining the portfolio together before the analysis as suggested by TA
import pandas as pd
import numpy as np
from datetime import datetime

# Define the portfolio and historical dataframes
portfolio = {"JNJ": 1.2*10**6,
             "MRK": 2.5*10**6,
             "PFE": 3.5*10**6
            }
JNJ = pd.read_csv("hw3_JNJ.csv")
MRK = pd.read_csv("hw3_MRK.csv")
PFE = pd.read_csv("hw3_PFE.csv")

# Use the most recent market price as the current market price
current_prices = {"JNJ": JNJ.iloc[-1]["Adj Close"],
                  "MRK": MRK.iloc[-1]["Adj Close"],
                  "PFE": PFE.iloc[-1]["Adj Close"]
                 }

current_portfolio_price = current_prices["JNJ"]*1200000 + current_prices["MRK"]*2500000 + current_prices["PFE"]*3500000

portfolio = JNJ["Adj Close"]*1200000 + MRK["Adj Close"]*2500000 + PFE["Adj Close"]*3500000

portfolio_preds = []
portfolio_rates = []
portfolio_pos_future = []

for i in range(-2,-len(JNJ),-1):
    portfolio_cur = portfolio.iloc[i]
    portfolio_prev = portfolio.iloc[i-1]
    portfolio_change = np.log(portfolio_cur) - np.log(portfolio_prev)
    portfolio_pred = current_portfolio_price*np.exp(portfolio_change)
    portfolio_preds.append(portfolio_pred)
    portfolio_rates.append(portfolio_change)
    portfolio_pos_future.append(portfolio_pred - current_portfolio_price)
    
confidence_level = 0.99
one_day_VaR = np.percentile(portfolio_pos_future, 0.99)
one_day_VaR

-18861114.460402917

These above approaches are equivalent, and the other methods are suggested by the TA. I thought it will be okay to keep both solutions in there just in case.

(c) Reasoning

The two different VaR results that we obtained using the parametric VaR and the historical VaR are likely to be different due to the underlying assumptions and methodologies of the two approaches.

The parametric VaR approach relies on the normality assumption of the returns distribution and uses a covariance matrix to estimate the variance of the portfolio. This approach can be relatively quick and easy to compute, but its accuracy depends heavily on the normality assumption and the quality of the estimated covariance matrix.

On the other hand, the historical VaR approach is a non-parametric approach that does not require any assumptions about the underlying distribution of returns. Instead, it uses the historical returns data to estimate the loss distribution of the portfolio, and can provide a more accurate estimate of VaR in situations where the returns distribution is not normal or when there is a lack of data on the estimated covariance matrix.

In general, it is recommended to use a combination of different VaR approaches to gain a more complete understanding of the portfolio's risk profile. This can include stress-testing the portfolio using different scenarios, such as extreme market events, as well as using other risk metrics such as expected shortfall or conditional VaR.

Ultimately, the choice of which VaR approach to use will depend on the risk manager's specific needs and the characteristics of the portfolio being evaluated. It is important for the risk manager to carefully consider the assumptions and limitations of each method and to use multiple approaches to validate the results. 

But, I would advise the risk manager to consider using the parametric approach instead of the historical approach for calculating the 99% VaR. This is because the historical approach relies heavily on the limited data available and can produce unrealistic price changes if only a few exceptional cases occurred in the past. On the other hand, the parametric approach takes into account the properties of the entire dataset, rather than focusing on isolated extreme events, making it a more reliable prediction method.

# Question 2

In [ ]:
# attached to this. Please turn over!